### ISSUE TITLE
Aimbot does not work

### ISSUE THREAD

**Issue by Factory69420** [massas0/massashook#1]
I changed alot of the menu stuff and chat spam to make it a meme cheat but I noticed the aimbot does not lock on to anyone. I never touched any real code. P.s what is "anti pasta"

**Comment by massas0** [comment]
Thats the anti pasta. change the Line 23 of CreateMove.h to 		CInput::CUserCmd *cmd = g_Input->GetUserCmd(0, sequence_number);
